### ISSUE TITLE
`structuredClone` polyfill is broken

### ISSUE THREAD

**Issue by romainmenke** [Financial-Times/polyfill-library#1269]
see : https://github.com/Financial-Times/polyfill-library/actions/runs/3981951365

pr : https://github.com/Financial-Times/polyfill-library/pull/1242

@CheloXL @JakeChampion It seems that there are some differences between browser versions in serialize/deserialize.

In Chrome 48 for example one part is a string and the other is true `null` :
<img width="564" alt="Screenshot 2023-01-29 at 18 10 14" src="https://user-images.githubusercontent.com/11521496/215343445-9b83f13a-fcf2-469c-8b0b-80f3f9aa3e22.png">

Does anyone have time to resolve these issues?
If not, we should revert these changes until someone does have time.

**Comment by romainmenke** [comment]
config.toml is also not fully correct.
Fixed stats :

```toml
[browsers]
android = "*"
bb = "*"
chrome = "<98"
edge = "*"
edge_mob = "*"
firefox = "<94"
firefox_mob = "<94"
ie = "*"
ie_mob = "*"
opera = "<84"
op_mob = "<68"
op_mini = "*"
safari = "<15.4"
ios_saf = "<15.4"
samsung_mob = "<18.0"
```
